### ISSUE TITLE
Click/Touch and swipe layout at the same time

### ISSUE THREAD

**Issue by songsofwingspan** [dominikprzywara/Torman.Swipeable#1]
Is there a way to receive touch/click events on list items while using the swipe layout at the same time?
When trying to use Touch listener on the list item at the same time with swipe layout, the swipe to dismiss feature is not working anymore.
And when trying the same thing with Click Listener, the event for click is never being called.

**Comment by songsofwingspan** [comment]
Or let's put it in other words: As soon as I'm using Swipeable ListView `listview.ItemClick` is never called. Is this Intentionally?

**Comment by dominikprzywara** [comment]
Hi,

I haven't touched Xamarin for the last 4 years or so, but I remember that there were some issues back in the days with `listview.ItemClick` - no idea whether it was resolved or not. You can overcome this by subscribing to `TopViewClick` in you Adapter in `GetView` like this:

```cs
public override View GetView(int position, View convertView, ViewGroup parent)
{
    var swipeableView = convertView as SwipeLayout;

    if (swipeableView == null)
    {
        swipeableView = new SwipeLayout(context);
    }

    var topView = swipeableView.SetTopView(Resource.Layout.Main);
    swipeableView.TopViewClick -= TopViewClick;
    swipeableView.TopViewClick += TopViewClick;
    topView.FindViewById<TextView>(Resource.Id.textView).Text = array[position];
    
 ...
}
```

If you want to fix this issue feel free to leave PR :)
